---
apiVersion: v1
kind: Namespace
metadata:
  name: atlant-dev-ns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atlant-cfg-map
  namespace: atlant-dev-ns
data:
  config.json: |
     {
        "subscription_key": "ATLANT-LICENSE-KEY",
        "scanning": {
            "http_endpoints": [
                {
                    "address": "0.0.0.0",
                    "port": 8081
                }
            ]
        },
        "authentication": {
            "method": "api_key",
            "api_key": "6f082ace-1a8d-4f6d-a6f0-bd24076e8d7d"
        }
     }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlant-deployment
  namespace: atlant-dev-ns
  labels:
    app: atlant
spec:
  replicas: 3
  selector:
    matchLabels:
      app: atlant
  template:
    metadata:
      labels:
        app: atlant
    spec:
      containers:
      - name: atlant-container
        image: public.ecr.aws/withsecure/atlant:latest
        resources:
          # Resource consumption depends on configuration
          # (for example how deeply archives should be scanned)
          # and files to scan (size, archives depth, number of simultaneous requests per pod).
          # This is an example for medium sized zip bomb.
          requests:
            memory: "2048Mi"
            cpu: "500m"
          limits:
            memory: "8192Mi"
            cpu: "2000m"
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8081
        readinessProbe:
          # Wait for default virus definitions update
          exec:
            command:
            - /bin/bash
            - -c
            - "[ -z $(/opt/withsecure/atlant/bin/update --list --no-lock | tr -d ' \n\r ') ]"
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /api/status/v1
            port: 8081
            httpHeaders:
            - name: X-Api-Key
              value: 6f082ace-1a8d-4f6d-a6f0-bd24076e8d7d
          initialDelaySeconds: 180
          periodSeconds: 1800
          timeoutSeconds: 10
          failureThreshold: 1
        volumeMounts:
        - name: atlant-cfg-volume
          mountPath: "/etc/opt/withsecure/atlant/config"
          readOnly: true
      volumes:
      - name: atlant-cfg-volume
        configMap:
          name: atlant-cfg-map
          items:
          - key: "config.json"
            path: "config.json"

---
apiVersion: v1
kind: Service
metadata:
  name: atlant-service
  namespace: atlant-dev-ns
spec:
  selector:
    app: atlant
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 31273
  type: LoadBalancer
